services:
  gravit-server-prod:
    container_name: gravit-server-prod
    image: ${DOCKER_HUB_USERNAME}/gravit-server:prod
    ports:
      - "8520:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILE=prod
    networks:
      - gravit-prod
    volumes:
      - ./logs:/var/log/spring
    depends_on:
      gravit-redis-prod:
        condition: service_started


  gravit-redis-prod:
    container_name: gravit-redis-prod
    image: redis:latest
    ports:
      - "6388:6379"
    volumes:
      - redis_data:/data
    networks:
      - gravit-prod
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./logs:/var/log/spring
      - ./infra/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=production
    command: [ "run", "/etc/alloy/config.alloy" ]
    networks:
      - gravit-prod

networks:
  gravit-prod: