name: CI pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: 테스트 코드 실행
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 버전 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 테스트 실행
        run: |
          chmod +x ./gradlew
          ./gradlew --info test

      - name: 테스트 결과 출력
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/test/TEST-*.xml